-- ============================================================
-- 991_migrate_eav.sql
--
-- [廃止] このファイルは旧 ctb_property テーブルへの移行スクリプトでしたが、
-- ctb_property は ctb_contract_property（303_ctb_tables.sql）に統合済みです。
--
-- 現在の移行フロー:
--   d_kykh/d_kykm → sp_migrate_d_kykh_to_ctb() → ctb_contract_property
--   EAV属性は 905_testdata_property.sql で投入
--
-- このファイルは参考として残しています。実行しないでください。
-- ============================================================
