-- ============================================================
-- LeaseM4BS KITOKU固定長出力用ワークテーブル DDL
-- Access版 tw_KITOKU_CMSW2WRK / APGDHWRK / APGDDWRK / APGDSWRK 相当
-- pc_仕訳出力 の固定長テキスト出力元データ
-- ============================================================

BEGIN;

SET search_path TO public;

-- ============================================================
-- ワークテーブル削除
-- ============================================================
DROP TABLE IF EXISTS public.tw_kitoku_apgdswrk CASCADE;
DROP TABLE IF EXISTS public.tw_kitoku_apgddwrk CASCADE;
DROP TABLE IF EXISTS public.tw_kitoku_apgdhwrk CASCADE;
DROP TABLE IF EXISTS public.tw_kitoku_cmsw2wrk CASCADE;

-- ============================================================
-- tw_kitoku_cmsw2wrk: 伝票ワーク (52フィールド, レコード長571バイト)
-- ============================================================
CREATE TABLE public.tw_kitoku_cmsw2wrk (
    id                  SERIAL PRIMARY KEY,
    sw2_kai_code        VARCHAR(5),
    sw2_date            VARCHAR(10),
    sw2_den_no          VARCHAR(8),
    sw2_gyo_no          INTEGER,
    sw2_dc_kbn          VARCHAR(1),
    sw2_kmk_code        VARCHAR(10),
    sw2_hkm_code        VARCHAR(10),
    sw2_bmn_code        VARCHAR(10),
    sw2_code1           VARCHAR(10),
    sw2_code2           VARCHAR(10),
    sw2_code3           VARCHAR(10),
    sw2_code4           VARCHAR(10),
    sw2_kin             DOUBLE PRECISION DEFAULT 0,
    sw2_zei_code        VARCHAR(4),
    sw2_zei_kbn         VARCHAR(1),
    sw2_zei_kin         DOUBLE PRECISION DEFAULT 0,
    sw2_cur_code        VARCHAR(3),
    sw2_rate_type       VARCHAR(2),
    sw2_rate            DOUBLE PRECISION DEFAULT 0,
    sw2_cur_kin         DOUBLE PRECISION DEFAULT 0,
    sw2_tekiyo1         VARCHAR(40),
    sw2_tekiyo2         VARCHAR(40),
    sw2_grp_code        VARCHAR(2),
    sw2_sys_kbn         VARCHAR(2),
    sw2_sys_den_no      VARCHAR(8),
    sw2_sys_sys_kbn     VARCHAR(2),
    sw2_sys_grp_code    VARCHAR(2),
    sw2_ait_kmk_code    VARCHAR(10),
    sw2_ait_hkm_code    VARCHAR(10),
    sw2_usr_id1         VARCHAR(10),
    sw2_sts_no1         VARCHAR(3),
    sw2_sys_date1       VARCHAR(10),
    sw2_usr_id2         VARCHAR(10),
    sw2_sts_no2         VARCHAR(3),
    sw2_sys_date2       VARCHAR(10),
    sw2_shonin_kbn      VARCHAR(1),
    sw2_den_kbn         VARCHAR(1),
    sw2_haifu_kbn       VARCHAR(1),
    sw2_rec_level       VARCHAR(1),
    sw2_tori_kbn        VARCHAR(1),
    sw2_tori_code       VARCHAR(20),
    sw2_yobi_char1      VARCHAR(10),
    sw2_yobi_char2      VARCHAR(10),
    sw2_yobi_char3      VARCHAR(10),
    sw2_yobi_char4      VARCHAR(10),
    sw2_yobi_char5      VARCHAR(20),
    sw2_yobi_char6      VARCHAR(20),
    sw2_yobi_char7      VARCHAR(20),
    sw2_yobi_char8      VARCHAR(20),
    sw2_yobi_num1       DOUBLE PRECISION DEFAULT 0,
    sw2_yobi_num2       DOUBLE PRECISION DEFAULT 0,
    sw2_yobi_num3       DOUBLE PRECISION DEFAULT 0
);

CREATE INDEX idx_tw_kitoku_cmsw2wrk_den ON public.tw_kitoku_cmsw2wrk (sw2_den_no, sw2_dc_kbn, sw2_gyo_no);

-- ============================================================
-- tw_kitoku_apgdhwrk: 金額概要ワーク (72フィールド)
-- ============================================================
CREATE TABLE public.tw_kitoku_apgdhwrk (
    id                      SERIAL PRIMARY KEY,
    gdh_kai_code            VARCHAR(5),
    gdh_den_kbn             VARCHAR(2),
    gdh_grp_code            VARCHAR(2),
    gdh_den_no              VARCHAR(8),
    gdh_den_date            VARCHAR(10),
    gdh_sh_saki_kbn         VARCHAR(1),
    gdh_sir_code            VARCHAR(20),
    gdh_kei_kin             DOUBLE PRECISION DEFAULT 0,
    gdh_kabu_kbn            VARCHAR(1),
    gdh_sai_kin             DOUBLE PRECISION DEFAULT 0,
    gdh_sai_nuki_kin        DOUBLE PRECISION DEFAULT 0,
    gdh_sai_zei_kin         DOUBLE PRECISION DEFAULT 0,
    gdh_tekiyo              VARCHAR(40),
    gdh_sei_no              VARCHAR(15),
    gdh_sei_date            VARCHAR(10),
    gdh_cycle_kbn           VARCHAR(1),
    gdh_den_syurui          VARCHAR(1),
    gdh_dc_hanten           VARCHAR(1),
    gdh_shz_den_kbn         VARCHAR(1),
    gdh_sosai_kbn           VARCHAR(1),
    gdh_utibarai_kbn        VARCHAR(1),
    gdh_sai_kmk_code        VARCHAR(10),
    gdh_sai_hkm_code        VARCHAR(10),
    gdh_sai_bmn_code        VARCHAR(10),
    gdh_sai_fc1_code        VARCHAR(10),
    gdh_sai_fc2_code        VARCHAR(10),
    gdh_sai_fc3_code        VARCHAR(10),
    gdh_sai_fc4_code        VARCHAR(10),
    gdh_sai_zei_code        VARCHAR(4),
    gdh_sai_zei_kbn         VARCHAR(1),
    gdh_sai_tekiyo          VARCHAR(40),
    gdh_cur_code            VARCHAR(3),
    gdh_rate_type           VARCHAR(2),
    gdh_rate                DOUBLE PRECISION DEFAULT 0,
    gdh_cur_kin             VARCHAR(22),
    gdh_rpl_usr_id          VARCHAR(10),
    gdh_rpl_sts_no          VARCHAR(3),
    gdh_rpl_date            VARCHAR(10),
    gdh_spot_kbn            VARCHAR(1),
    gdh_kijitu_kbn          VARCHAR(1),
    gdh_furi_kmk_code       VARCHAR(10),
    gdh_furi_hkm_code       VARCHAR(10),
    gdh_furi_fc1_code       VARCHAR(10),
    gdh_furi_fc2_code       VARCHAR(10),
    gdh_furi_fc3_code       VARCHAR(10),
    gdh_furi_fc4_code       VARCHAR(10),
    gdh_rec_level           VARCHAR(1),
    gdh_kari_kmk_code       VARCHAR(10),
    gdh_kari_hkm_code       VARCHAR(10),
    gdh_kari_bmn_code       VARCHAR(10),
    gdh_kari_fc1_code       VARCHAR(10),
    gdh_kari_fc2_code       VARCHAR(10),
    gdh_kari_fc3_code       VARCHAR(10),
    gdh_kari_fc4_code       VARCHAR(10),
    gdh_kari_zei_code       VARCHAR(4),
    gdh_kari_zei_kbn        VARCHAR(1),
    gdh_kari_tekiyo         VARCHAR(40),
    gdh_kari_kin            DOUBLE PRECISION DEFAULT 0,
    gdh_kari_nuki_kin       DOUBLE PRECISION DEFAULT 0,
    gdh_kari_zei_kin        DOUBLE PRECISION DEFAULT 0,
    gdh_kari_cur_kin        DOUBLE PRECISION DEFAULT 0,
    gdh_furi_kmk_tori_kbn   VARCHAR(1),
    gdh_furi_kmk_tori_code  VARCHAR(20),
    gdh_kari_kmk_tori_kbn   VARCHAR(1),
    gdh_kari_kmk_tori_code  VARCHAR(20),
    gdh_sai_kmk_tori_kbn    VARCHAR(1),
    gdh_sai_kmk_tori_code   VARCHAR(20),
    gdh_yobi_char1          VARCHAR(10),
    gdh_yobi_char2          VARCHAR(10),
    gdh_yobi_char3          VARCHAR(10),
    gdh_yobi_char4          VARCHAR(10),
    gdh_yobi_char5          VARCHAR(20),
    gdh_yobi_char6          VARCHAR(20),
    gdh_yobi_char7          VARCHAR(20),
    gdh_yobi_char8          VARCHAR(20),
    gdh_yobi_num1           DOUBLE PRECISION DEFAULT 0,
    gdh_yobi_num2           DOUBLE PRECISION DEFAULT 0,
    gdh_yobi_num3           DOUBLE PRECISION DEFAULT 0,
    gdh_sosai_rate_type     VARCHAR(2),
    gdh_sosai_rate          DOUBLE PRECISION DEFAULT 0,
    gdh_sosai_kin           VARCHAR(22)
);

CREATE INDEX idx_tw_kitoku_apgdhwrk_den ON public.tw_kitoku_apgdhwrk (gdh_den_no);

-- ============================================================
-- tw_kitoku_apgddwrk: 金額詳細ワーク (31フィールド)
-- ============================================================
CREATE TABLE public.tw_kitoku_apgddwrk (
    id                  SERIAL PRIMARY KEY,
    gdd_kai_code        VARCHAR(5),
    gdd_den_kbn         VARCHAR(2),
    gdd_grp_code        VARCHAR(2),
    gdd_den_no          VARCHAR(8),
    gdd_den_date        VARCHAR(10),
    gdd_gyo_no          INTEGER,
    gdd_kmk_code        VARCHAR(10),
    gdd_hkm_code        VARCHAR(10),
    gdd_bmn_code        VARCHAR(10),
    gdd_fc1_code        VARCHAR(10),
    gdd_fc2_code        VARCHAR(10),
    gdd_fc3_code        VARCHAR(10),
    gdd_fc4_code        VARCHAR(10),
    gdd_nuki_kin        DOUBLE PRECISION DEFAULT 0,
    gdd_zei_code        VARCHAR(4),
    gdd_zei_kbn         VARCHAR(1),
    gdd_zei_kin         DOUBLE PRECISION DEFAULT 0,
    gdd_cur_kin         VARCHAR(22),
    gdd_tekiyo          VARCHAR(40),
    gdd_tori_kbn        VARCHAR(1),
    gdd_tori_code       VARCHAR(20),
    gdd_yobi_char1      VARCHAR(10),
    gdd_yobi_char2      VARCHAR(10),
    gdd_yobi_char3      VARCHAR(10),
    gdd_yobi_char4      VARCHAR(10),
    gdd_yobi_char5      VARCHAR(20),
    gdd_yobi_char6      VARCHAR(20),
    gdd_yobi_char7      VARCHAR(20),
    gdd_yobi_char8      VARCHAR(20),
    gdd_yobi_num1       DOUBLE PRECISION DEFAULT 0,
    gdd_yobi_num2       DOUBLE PRECISION DEFAULT 0,
    gdd_yobi_num3       DOUBLE PRECISION DEFAULT 0,
    gdd_rate_type       VARCHAR(2),
    gdd_rate            DOUBLE PRECISION DEFAULT 0
);

CREATE INDEX idx_tw_kitoku_apgddwrk_den ON public.tw_kitoku_apgddwrk (gdd_den_no, gdd_gyo_no);

-- ============================================================
-- tw_kitoku_apgdswrk: 支払ワーク (62フィールド)
-- ============================================================
CREATE TABLE public.tw_kitoku_apgdswrk (
    id                      SERIAL PRIMARY KEY,
    gds_kai_code            VARCHAR(5),
    gds_den_kbn             VARCHAR(2),
    gds_grp_code            VARCHAR(2),
    gds_den_no              VARCHAR(8),
    gds_den_date            VARCHAR(10),
    gds_gyo_no              INTEGER,
    gds_sh_kin              DOUBLE PRECISION DEFAULT 0,
    gds_shy_date            VARCHAR(10),
    gds_sh_hoho             VARCHAR(2),
    gds_sh_tekiyo           VARCHAR(40),
    gds_kgg_code            VARCHAR(10),
    gds_cur_kin             VARCHAR(22),
    gds_koz_knr_code        VARCHAR(4),
    gds_frj_code            VARCHAR(4),
    gds_fsaki_bnk_code      VARCHAR(4),
    gds_fsaki_brh_code      VARCHAR(3),
    gds_fsaki_koz_syubetsu  VARCHAR(2),
    gds_fsaki_koz_no        VARCHAR(7),
    gds_fsaki_koz_name      VARCHAR(40),
    gds_fsaki_koz_name_fb   VARCHAR(30),
    gds_tesu_kbn            VARCHAR(1),
    gds_kyujitsu_kbn        VARCHAR(1),
    gds_dsi_kbn             VARCHAR(1),
    gds_tega_koz_code       VARCHAR(4),
    gds_tega_watasi_code    VARCHAR(10),
    gds_tega_no             VARCHAR(10),
    gds_tega_syurui         VARCHAR(1),
    gds_fdasi_kbn           VARCHAR(1),
    gds_fdasi_date          VARCHAR(10),
    gds_tega_mankibi        VARCHAR(10),
    gds_tega_hakko_kbn      VARCHAR(1),
    gds_kijitu_yotei_date   VARCHAR(10),
    gds_tega_bmn_code       VARCHAR(10),
    gds_azu_kbn             VARCHAR(1),
    gds_azu_kmk_code        VARCHAR(10),
    gds_azu_hkm_code        VARCHAR(10),
    gds_azu_bmn_code        VARCHAR(10),
    gds_azu_fc1_code        VARCHAR(10),
    gds_azu_fc2_code        VARCHAR(10),
    gds_azu_fc3_code        VARCHAR(10),
    gds_azu_fc4_code        VARCHAR(10),
    gds_azu_zei_code        VARCHAR(4),
    gds_azu_zei_kbn         VARCHAR(1),
    gds_azu_tekiyo          VARCHAR(40),
    gds_azu_kin             VARCHAR(22),
    gds_azu_nuki_kin        VARCHAR(22),
    gds_azu_zei_kin         VARCHAR(22),
    gds_azu_cur_kin         VARCHAR(22),
    gds_tyo_sh_kin          DOUBLE PRECISION DEFAULT 0,
    gds_azu_kmk_tori_kbn    VARCHAR(1),
    gds_azu_kmk_tori_code   VARCHAR(20),
    gds_yobi_char1          VARCHAR(10),
    gds_yobi_char2          VARCHAR(10),
    gds_yobi_char3          VARCHAR(10),
    gds_yobi_char4          VARCHAR(10),
    gds_yobi_char5          VARCHAR(20),
    gds_yobi_char6          VARCHAR(20),
    gds_yobi_char7          VARCHAR(20),
    gds_yobi_char8          VARCHAR(20),
    gds_yobi_num1           DOUBLE PRECISION DEFAULT 0,
    gds_yobi_num2           DOUBLE PRECISION DEFAULT 0,
    gds_yobi_num3           DOUBLE PRECISION DEFAULT 0,
    gds_tega_no_eda         VARCHAR(5)
);

CREATE INDEX idx_tw_kitoku_apgdswrk_den ON public.tw_kitoku_apgdswrk (gds_den_no, gds_gyo_no);

COMMIT;
